=== VilRan/Legatus/Fortress/Settings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Settings"
    xmlns="Conquest"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="Settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Localization"></xs:element>
        <xs:element name="Display">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Mode"></xs:element>
              <xs:element name="Width"></xs:element>
              <xs:element name="Height"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Mods">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Mod" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== VilRan/Legatus/Fortress/Settings.xml
<?xml version="1.0" encoding="utf-8" ?>
<Settings
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="Conquest Settings.xsd"
  >
  <Localization>English</Localization>
  <Display>
    <Mode>Borderless</Mode><!-- Fullscreen, Windowed or Borderless. Defaults to Borderless if empty or invalid.-->
    <Width></Width><!-- In pixels. Defaults to desktop width. -->
    <Height></Height><!-- In pixels. Defaults to desktop height. -->
  </Display>
  <Mods>
    <!--Mods that are active by default. Order matters; mods further down will override earlier ones if there are any conflicts.-->
    <Mod>DefaultGraphics</Mod>
    <Mod>DefaultRuleset</Mod>
  </Mods>
</Settings>
